{
 "title": "AWS Resource Monitoring",
 "description": "Track metrics for services running on AWS using CloudWatch metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "PingURL",
    "label": "UptimeURL",
    "query": "SHOW TAG VALUES FROM \"ping\" WITH KEY = \"url\""
   },
   {
    "name": "loadbalancername",
    "label": "Load Balancer",
    "query": "dimension_values($region,AWS/ApplicationELB,ActiveConnectionCount,LoadBalancer)"
   },
   { "name": "region", "label": "Region", "query": "regions()" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT 100 - mean(\"percent_packet_loss\") FROM \"ping\" WHERE \"url\" =~ /^$PingURL$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "208.67.222.222" }
     ]
    }
   ]
  },
  {
   "title": "Site traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{namespace}} - {{label}}",
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "*", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "{{namespace}} - {{label}}",
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "*", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$PingURL$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT 100 - mean(\"percent_packet_loss\") FROM \"ping\" WHERE \"url\" =~ /^$PingURL$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "208.67.222.222" }
     ]
    }
   ]
  },
  {
   "title": "Ping Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$PingURL$/" }
     ]
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{namespace}} - {{label}} - {{metric}}",
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "*", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT 100 - mean(\"percent_packet_loss\") FROM \"ping\" WHERE \"url\" =~ /^$PingURL$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "208.67.222.222" }
     ]
    }
   ]
  },
  {
   "title": "Packet Loss Percentage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT max(\"percent_packet_loss\") FROM \"ping\" WHERE \"url\" = '208.67.222.222' AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$PingURL$/" }
     ]
    }
   ]
  },
  {
   "title": "TotalErrorRate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 5, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{namespace}} - {{label}} - {{metric}}",
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "*", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${LABEL} - ${PROP('MetricName')}",
     "metricName": "TotalErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CloudFront 5xx Issues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{namespace}} - {{label}} - {{metric}}",
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "*", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "5xxErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CloudFront 4xx Issues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{namespace}} - {{label}} - {{metric}}",
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "*", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "4xxErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ELB Application Load Balancer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTPCode_Target 5xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "HTTPCode_Target_5XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "HTTPCode_Target 4xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL} - ${PROP('MetricName')}",
       "metricName": "HTTPCode_ELB_4XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "HTTPCode_Target 3xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL} - ${PROP('MetricName')}",
       "metricName": "HTTPCode_ELB_3XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "HTTPCode_ELB 5xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL} - ${PROP('MetricName')}",
       "metricName": "HTTPCode_ELB_5XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "HTTPCode_ELB 4xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "- ${LABEL} - ${PROP('MetricName')}",
       "metricName": "HTTPCode_ELB_4XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "HTTPCode_ELB 3xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL} - ${PROP('MetricName')}",
       "metricName": "HTTPCode_ELB_3XX_Count",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "ConsumedLBCapacityUnits / ConsumedLCUs / ProcessedBytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "{{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ConsumedLBCapacityUnits",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ProcessedBytes",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      },
      {
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ConsumedLCUs",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "ConnectionCount",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ActiveConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      },
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "NewConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      },
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "RejectedConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      },
      {
       "alias": "{{label}} ",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TargetConnectionErrorCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "RequestCount / TargetResponseTime",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "RequestCount",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Sum"
      },
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TargetResponseTime",
       "namespace": "AWS/ApplicationELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "NLB Network Load Balancer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Healthy Hosts Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*", "TargetGroup": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "HealthyHostCount",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Unhealthy Hosts Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*", "TargetGroup": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "UnHealthyHostCount",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "TCP",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TCP_Client_Reset_Count",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Sum"
      },
      {
       "alias": "{{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TCP_ELB_Reset_Count",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Sum"
      },
      {
       "alias": "{{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "TCP_Target_Reset_Count",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "ConsumedLCUs / ProcessedBytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ProcessedBytes",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      },
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ConsumedLCUs",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Net /Active Flow Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "ActiveFlowCount",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Sum"
      },
      {
       "alias": "{{label}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancer": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "NewFlowCount",
       "namespace": "AWS/NetworkELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "ELB Clasic Load Balancer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HealthyHostCount",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL} - ${PROP('MetricName')}",
       "metricName": "HealthyHostCount",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "UnHealthyHostCount",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL} - ${PROP('MetricName')}",
       "metricName": "UnHealthyHostCount",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "Latency",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "RequestCount",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "RequestCount",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "BackendConnectionErrors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "BackendConnectionErrors",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "SpilloverCount / SurgeQueueLength",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL} - ${PROP('MetricName')}",
       "metricName": "SpilloverCount",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "alias": "{{namespace}} - {{label}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL} - ${PROP('MetricName')}",
       "metricName": "SurgeQueueLength",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Maximum"
      }
     ]
    },
    {
     "title": "HTTPCode_Backend 5xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "HTTPCode_Backend_5XX",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "HTTPCode_Backend 4xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "HTTPCode_Backend_4XX",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "HTTPCode_Backend 3xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "HTTPCode_Backend_3XX",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "HTTPCode_ELB 5xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "HTTPCode_ELB_5XX",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "HTTPCode_ELB 4xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "HTTPCode_ELB_4XX",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "HTTPCode_Backend 2xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{namespace}} - {{metric}}",
       "application": { "filter": "" },
       "dimensions": { "LoadBalancerName": "$loadbalancername" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "label": "${LABEL}",
       "metricName": "HTTPCode_Backend_2XX",
       "namespace": "AWS/ELB",
       "options": {
        "showDisabledItems": false
       },
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Billing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Estimated charges",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "alias": "Total",
       "application": { "filter": "" },
       "dimensions": { "Currency": "USD" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "EstimatedCharges",
       "namespace": "AWS/Billing",
       "options": {
        "showDisabledItems": false
       },
       "region": "us-east-1",
       "statistic": "Average"
      },
      {
       "alias": "{{ServiceName}}",
       "application": { "filter": "" },
       "dimensions": { "Currency": "USD", "ServiceName": "*" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "metricName": "EstimatedCharges",
       "namespace": "AWS/Billing",
       "options": {
        "showDisabledItems": false
       },
       "region": "us-east-1",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Estimated daily charges",
     "type": "graph",
     "gridPos": { "h": 13, "w": 11, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "alias": "Total estimated daily charge",
       "application": { "filter": "" },
       "dimensions": { "Currency": "USD" },
       "expression": "IF(m2>0, m2)",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "id": "m3",
       "item": { "filter": "" },
       "metricEditorMode": 1,
       "metricName": "EstimatedCharges",
       "namespace": "AWS/Billing",
       "options": {
        "showDisabledItems": false
       },
       "period": "86400",
       "region": "us-east-1",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}